# Generated by Django 5.2.5 on 2025-10-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_motivationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('category', models.CharField(choices=[('success', 'Success'), ('perseverance', 'Perseverance'), ('learning', 'Learning'), ('focus', 'Focus'), ('motivation', 'Motivation'), ('productivity', 'Productivity'), ('general', 'General')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['?'],
            },
        ),
    ]
